server:
  port: 8086

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9093}

spring:
  application:
    name: routing-service

routing:
  provider:
    openrouteservice:
      api-key: ${OPENROUTESERVICE_API_KEY:}
      base-url: ${OPENROUTESERVICE_BASE_URL:https://api.openrouteservice.org}
