server:
  port: 8085

spring:
  application:
    name: notification-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:starlyvia}
    password: ${SPRING_DATASOURCE_PASSWORD:starlyvia}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: notification-service

app:
  kafka:
    topics:
      auth-events: auth.events
      group-events: group.events
      plan-events: plan.events
