server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${auth.service.url}
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - JwtValidation

auth:
  service:
    url: http://localhost:8081

jwt:
  secret: "starlyvia-super-secret-key-starlyvia-super-secret-key"
