server:
  port: 8082

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9092}

spring:
  application:
    name: group-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/group_db}
    username: ${SPRING_DATASOURCE_USERNAME:starlyvia}
    password: ${SPRING_DATASOURCE_PASSWORD:starlyvia}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

auth:
  grpc:
    host: ${AUTH_GRPC_HOST:localhost}
    port: ${AUTH_GRPC_PORT:9091}

app:
  kafka:
    enabled: ${APP_KAFKA_ENABLED:true}
    topics:
      group-events: group.events
